### ISSUE TITLE
New Pester Build Broke Tests

### ISSUE THREAD

**Issue by weswigham** [chrisbenti/PS-Config#21]
Looks like it's more stringent about some things, like when you Mock.

**Comment by weswigham** [comment]
Strange, I fixed the pester assert pretty easily, but the complaint about .Count is... confusing? Get-Module's return always has a .Count locally. What's up on appveyor?

**Comment by chrisbenti** [comment]
How did you fix the first one?

**Comment by weswigham** [comment]
Moved the mock definitions into the defines.

**Comment by weswigham** [comment]
Think i got it all in my branch, waiting for build
