### ISSUE TITLE
posh-hg/posh-svn prompt tags don't appear in ConEmu

### ISSUE THREAD

**Issue by weswigham** [chrisbenti/PS-Config#7]
The custom posh-git ones, ofc, do. Just wanted to note this for somewhere so I could fix it later.

**Comment by chrisbenti** [comment]
They won't appear in Powershell either I think. + TFS tags if we can find a way to do it.

**Comment by weswigham** [comment]
They appear in normal powershell (in my brief test), just not in the ConEmu type windows.

**Comment by chrisbenti** [comment]
Is this still true after the conemu/regular window fix?

**Comment by weswigham** [comment]
No; it works fine as long as you remember to not let the posh-hg/posh-git/posh-svn functions append to your existing profile a new prompt override. The existing one handles them all.

**Comment by chrisbenti** [comment]
Is there anything to do then? Maybe a doc item to not let the posh modules do that or just add the posh modules to the config?

**Comment by weswigham** [comment]
Either/or will work, didn't know if you wanted posh-svn and posh-hg added to your config by default.

**Comment by chrisbenti** [comment]
I'm thinking about adding them, and then only importing the modules if the relevant binary is on the path.

**Comment by weswigham** [comment]
That's a pretty fair assessment.
